//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONBOXAppl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONBOXAppl.Properties.HelpLinks", typeof(HelpLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/structural-elements/beams-from-walls.
        /// </summary>
        public static string btnCreateBeam {
            get {
                return ResourceManager.GetString("btnCreateBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/structural-elements/create-beams-for-entire-building.
        /// </summary>
        public static string btnCreateBeamsFromBuilding {
            get {
                return ResourceManager.GetString("btnCreateBeamsFromBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/structural-elements/beams-from-structural-columns.
        /// </summary>
        public static string btnCreateBeamsFromColumns {
            get {
                return ResourceManager.GetString("btnCreateBeamsFromColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/structural-elements/columns-from-cad.
        /// </summary>
        public static string btnCreateColumnsFromDwg {
            get {
                return ResourceManager.GetString("btnCreateColumnsFromDwg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/topography/surface-by-pointcloud.
        /// </summary>
        public static string btnCreateTopoFromPointCloud {
            get {
                return ResourceManager.GetString("btnCreateTopoFromPointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/topography/slope-grading-by-floors.
        /// </summary>
        public static string btnCreateToposolidGradingFromFloors {
            get {
                return ResourceManager.GetString("btnCreateToposolidGradingFromFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/modify-elements/copy-beams.
        /// </summary>
        public static string btnElementsCopyLevel {
            get {
                return ResourceManager.GetString("btnElementsCopyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/modify-elements/join-elements.
        /// </summary>
        public static string btnElmentsJoin {
            get {
                return ResourceManager.GetString("btnElmentsJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/modify-elements/join-selected-elements.
        /// </summary>
        public static string btnElmentsSelectJoin {
            get {
                return ResourceManager.GetString("btnElmentsSelectJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-beams.
        /// </summary>
        public static string btnRenumberBeams {
            get {
                return ResourceManager.GetString("btnRenumberBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-nearest-spaces.
        /// </summary>
        public static string btnRenumberBlockParking {
            get {
                return ResourceManager.GetString("btnRenumberBlockParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/clear-parking-numbering.
        /// </summary>
        public static string btnRenumberClearParking {
            get {
                return ResourceManager.GetString("btnRenumberClearParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-columns.
        /// </summary>
        public static string btnRenumberColumns {
            get {
                return ResourceManager.GetString("btnRenumberColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-columns-by-selection.
        /// </summary>
        public static string btnRenumberColumnsSelect {
            get {
                return ResourceManager.GetString("btnRenumberColumnsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-grids.
        /// </summary>
        public static string btnRenumberGrids {
            get {
                return ResourceManager.GetString("btnRenumberGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-parking-spaces.
        /// </summary>
        public static string btnRenumberParking {
            get {
                return ResourceManager.GetString("btnRenumberParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/manage/package-project.
        /// </summary>
        public static string btnRevitZip {
            get {
                return ResourceManager.GetString("btnRevitZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/topography/slope-grading-by-pads.
        /// </summary>
        public static string btnTopoSlope {
            get {
                return ResourceManager.GetString("btnTopoSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/modify-elements/join-elements.
        /// </summary>
        public static string sptJoinElements {
            get {
                return ResourceManager.GetString("sptJoinElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/renumber-columns.
        /// </summary>
        public static string sptRenumberColumns {
            get {
                return ResourceManager.GetString("sptRenumberColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onboxapp-onbox.gitbook.io/onboxapp/renumber-elements/parking.
        /// </summary>
        public static string sptRenumberParking {
            get {
                return ResourceManager.GetString("sptRenumberParking", resourceCulture);
            }
        }
    }
}
