//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONBOXAppl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONBOXAppl.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid structural beam families loaded on the project. Please, load a least one and try to use this command again..
        /// </summary>
        public static string BeamsForBuilding_NoBeamFamilyLoaded {
            get {
                return ResourceManager.GetString("BeamsForBuilding_NoBeamFamilyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beams.
        /// </summary>
        public static string BeamsForBuilding_Transaction {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid structural column families loaded on the project. Please, load a least one and try to use this command again..
        /// </summary>
        public static string BeamsFromCAD_NoColumnFamilyLoaded {
            get {
                return ResourceManager.GetString("BeamsFromCAD_NoColumnFamilyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to find any rectangular or circular 2D shapes in the selected instance. Please add these elements and try again..
        /// </summary>
        public static string BeamsFromCAD_NoValidCADElements {
            get {
                return ResourceManager.GetString("BeamsFromCAD_NoValidCADElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Columns.
        /// </summary>
        public static string BeamsFromCAD_RotateTransaction {
            get {
                return ResourceManager.GetString("BeamsFromCAD_RotateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CAD instance..
        /// </summary>
        public static string BeamsFromCAD_SelectCADInstance {
            get {
                return ResourceManager.GetString("BeamsFromCAD_SelectCADInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Columns.
        /// </summary>
        public static string BeamsFromCAD_Transaction {
            get {
                return ResourceManager.GetString("BeamsFromCAD_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This family was deleted from the project, please load the necessary families and click on the reload button on the floating window..
        /// </summary>
        public static string BeamsFromColumns_DeletedBeamFamily {
            get {
                return ResourceManager.GetString("BeamsFromColumns_DeletedBeamFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you are on 3d view to run this command..
        /// </summary>
        public static string BeamsFromColumns_Not3dView {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Not3dView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate a graphical view to run this command..
        /// </summary>
        public static string BeamsFromColumns_NotGraphicalView {
            get {
                return ResourceManager.GetString("BeamsFromColumns_NotGraphicalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the column to adjust its offset.
        /// </summary>
        public static string BeamsFromColumns_SelectColumnToOffset {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SelectColumnToOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first structural column.
        /// </summary>
        public static string BeamsFromColumns_SelectFirstColumn {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SelectFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first column or the last beam to adjust the offset..
        /// </summary>
        public static string BeamsFromColumns_SelectFirstColumnOrBeam {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SelectFirstColumnOrBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the second structural column..
        /// </summary>
        public static string BeamsFromColumns_SelectSecondColumn {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SelectSecondColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beam.
        /// </summary>
        public static string BeamsFromColumns_Transaction {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust offset.
        /// </summary>
        public static string BeamsFromColumns_Transaction_AdjustOffset {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Transaction_AdjustOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This family was deleted from the project, please load the necessary families and click on the reload button on the floating window..
        /// </summary>
        public static string BeamsFromWalls_DeletedBeamFamily {
            get {
                return ResourceManager.GetString("BeamsFromWalls_DeletedBeamFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate a graphical view to run this command..
        /// </summary>
        public static string BeamsFromWalls_NotGraphicalView {
            get {
                return ResourceManager.GetString("BeamsFromWalls_NotGraphicalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an architectural wall.
        /// </summary>
        public static string BeamsFromWalls_SelectArchitecturalWall {
            get {
                return ResourceManager.GetString("BeamsFromWalls_SelectArchitecturalWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an architectural wall from the linked model..
        /// </summary>
        public static string BeamsFromWalls_SelectWallFromLink {
            get {
                return ResourceManager.GetString("BeamsFromWalls_SelectWallFromLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beam.
        /// </summary>
        public static string BeamsFromWalls_Transaction {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some issues were found:.
        /// </summary>
        public static string Common_Issues {
            get {
                return ResourceManager.GetString("Common_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess.
        /// </summary>
        public static string Common_Sucess {
            get {
                return ResourceManager.GetString("Common_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a beam..
        /// </summary>
        public static string CopyBeamsToLevels_SelectBeam {
            get {
                return ResourceManager.GetString("CopyBeamsToLevels_SelectBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Beams.
        /// </summary>
        public static string CopyBeamsToLevels_Transaction {
            get {
                return ResourceManager.GetString("CopyBeamsToLevels_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Elements.
        /// </summary>
        public static string ElementJoin_JoinTransaction {
            get {
                return ResourceManager.GetString("ElementJoin_JoinTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Elements.
        /// </summary>
        public static string ElementJoin_Transaction {
            get {
                return ResourceManager.GetString("ElementJoin_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjoin Elements.
        /// </summary>
        public static string ElementJoin_UnJoinTransaction {
            get {
                return ResourceManager.GetString("ElementJoin_UnJoinTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Element.
        /// </summary>
        public static string ElementJoinSelect_JoinTransaction {
            get {
                return ResourceManager.GetString("ElementJoinSelect_JoinTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate a graphical view to run this command..
        /// </summary>
        public static string ElementJoinSelect_NotGraphicalView {
            get {
                return ResourceManager.GetString("ElementJoinSelect_NotGraphicalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select elements to join..
        /// </summary>
        public static string ElementJoinSelect_SelectElements {
            get {
                return ResourceManager.GetString("ElementJoinSelect_SelectElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjoin Element.
        /// </summary>
        public static string ElementJoinSelect_UnJoinTransaction {
            get {
                return ResourceManager.GetString("ElementJoinSelect_UnJoinTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Exceptions_Data {
            get {
                return ResourceManager.GetString("Exceptions_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Exceptions_Detail {
            get {
                return ResourceManager.GetString("Exceptions_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Exceptions_Help {
            get {
                return ResourceManager.GetString("Exceptions_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Exceptions_Location {
            get {
                return ResourceManager.GetString("Exceptions_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Exceptions_Message {
            get {
                return ResourceManager.GetString("Exceptions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Exceptions_Source {
            get {
                return ResourceManager.GetString("Exceptions_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip File.
        /// </summary>
        public static string PackageProject_FileTypeName {
            get {
                return ResourceManager.GetString("PackageProject_FileTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the project before using this command..
        /// </summary>
        public static string PackageProject_SaveProjectFirst {
            get {
                return ResourceManager.GetString("PackageProject_SaveProjectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid structural beam families loaded on the project. Please, load a least one and try to use this command again..
        /// </summary>
        public static string RenumberBeams_NoBeamFamilyLoaded {
            get {
                return ResourceManager.GetString("RenumberBeams_NoBeamFamilyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Beams.
        /// </summary>
        public static string RenumberBeams_RenumberBeams {
            get {
                return ResourceManager.GetString("RenumberBeams_RenumberBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid structural column families loaded on the project. Please, load a least one and try to use this command again..
        /// </summary>
        public static string RenumberColumns_NoColumnFamilyLoaded {
            get {
                return ResourceManager.GetString("RenumberColumns_NoColumnFamilyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, before renumbering the columns click on the &apos;Guess&apos; button or insert the number manually..
        /// </summary>
        public static string RenumberColumns_NoGuess {
            get {
                return ResourceManager.GetString("RenumberColumns_NoGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to be on a plan view to run this command..
        /// </summary>
        public static string RenumberColumns_NotPlanView {
            get {
                return ResourceManager.GetString("RenumberColumns_NotPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Numbering from Columns.
        /// </summary>
        public static string RenumberColumns_RemoveNumbers_Transaction {
            get {
                return ResourceManager.GetString("RenumberColumns_RemoveNumbers_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first column to renumber..
        /// </summary>
        public static string RenumberColumns_SelectFirstColumn {
            get {
                return ResourceManager.GetString("RenumberColumns_SelectFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the row of structural columns..
        /// </summary>
        public static string RenumberColumns_SelectTheRowOfColumns {
            get {
                return ResourceManager.GetString("RenumberColumns_SelectTheRowOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Columns.
        /// </summary>
        public static string RenumberColumns_Transaction {
            get {
                return ResourceManager.GetString("RenumberColumns_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to find any grids in the project, please create them and run the command again..
        /// </summary>
        public static string RenumberGrids_NoGrids {
            get {
                return ResourceManager.GetString("RenumberGrids_NoGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are one or more grids with the same new numbering, please click on renumber table button or change them manually..
        /// </summary>
        public static string RenumberGrids_SameNumbering {
            get {
                return ResourceManager.GetString("RenumberGrids_SameNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Grids.
        /// </summary>
        public static string RenumberGrids_Transaction {
            get {
                return ResourceManager.GetString("RenumberGrids_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Names.
        /// </summary>
        public static string RenumberGrids_Transaction_AdjustNames {
            get {
                return ResourceManager.GetString("RenumberGrids_Transaction_AdjustNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Parking Numbering.
        /// </summary>
        public static string RenumberParking_ClearParkNumbering {
            get {
                return ResourceManager.GetString("RenumberParking_ClearParkNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input a valid integer number..
        /// </summary>
        public static string RenumberParking_IntegerNumber {
            get {
                return ResourceManager.GetString("RenumberParking_IntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to find any parking spaces in the project, please create them and run this command again..
        /// </summary>
        public static string RenumberParking_NoParking {
            get {
                return ResourceManager.GetString("RenumberParking_NoParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to be on a plan view to run this command..
        /// </summary>
        public static string RenumberParking_NotPlanView {
            get {
                return ResourceManager.GetString("RenumberParking_NotPlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the first parking space or change the order of numbering..
        /// </summary>
        public static string RenumberParking_SelectFirstOrChangeNumbering {
            get {
                return ResourceManager.GetString("RenumberParking_SelectFirstOrChangeNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first parking space.
        /// </summary>
        public static string RenumberParking_SelectFirstParkingSpace {
            get {
                return ResourceManager.GetString("RenumberParking_SelectFirstParkingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parking space.
        /// </summary>
        public static string RenumberParking_SelectParkingSpace {
            get {
                return ResourceManager.GetString("RenumberParking_SelectParkingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Parking Spaces.
        /// </summary>
        public static string RenumberParking_Transaction {
            get {
                return ResourceManager.GetString("RenumberParking_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found! Please, reinstall the app or download a new version at http://www.onboxdesign.com.br/.
        /// </summary>
        public static string SampleProjects_DirNotFound {
            get {
                return ResourceManager.GetString("SampleProjects_DirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to find building pads on the project..
        /// </summary>
        public static string SlopeGradingFromPads_NoPads {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_NoPads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to be on a 3D view to run this command..
        /// </summary>
        public static string SlopeGradingFromPads_Not3DView {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_Not3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to establish a toposurface associated with the pad, please recreate the pad to try again..
        /// </summary>
        public static string SlopeGradingFromPads_NoTopoAssociate {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_NoTopoAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to determine the outer limit of the pad, please try to recreate the pad..
        /// </summary>
        public static string SlopeGradingFromPads_OuterLoopIssue {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_OuterLoopIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to determine the offset from the outer limit of the pad, please try again with a simpler geometry..
        /// </summary>
        public static string SlopeGradingFromPads_OuterOffsetLoopIssue {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_OuterOffsetLoopIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pads with more than one upper face are not supported, please use a pad with only one upper face..
        /// </summary>
        public static string SlopeGradingFromPads_PadsWithMoreThanOneUpperFace {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_PadsWithMoreThanOneUpperFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a building pad..
        /// </summary>
        public static string SlopeGradingFromPads_SelectPad {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_SelectPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slope Grading.
        /// </summary>
        public static string SlopeGradingFromPads_Transaction {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper face of the pad must be planar..
        /// </summary>
        public static string SlopeGradingFromPads_UpperFaceNotPlanar {
            get {
                return ResourceManager.GetString("SlopeGradingFromPads_UpperFaceNotPlanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element selected..
        /// </summary>
        public static string TopoFromPointCloud_InvalidPointCloud {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_InvalidPointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of points reached, please change the iteration.
        /// </summary>
        public static string TopoFromPointCloud_MaxPointsReached {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_MaxPointsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of points reached, please change the iteration.
        /// </summary>
        public static string TopoFromPointCloud_MinPointsReached {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_MinPointsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to be on a 3D view to run this command..
        /// </summary>
        public static string TopoFromPointCloud_Not3DView {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_Not3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points to create the toposurface, please change the iteration settings and run this command again..
        /// </summary>
        public static string TopoFromPointCloud_NotEnoughPoints {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a pointcloud instance..
        /// </summary>
        public static string TopoFromPointCloud_SelectPointCloudInstance {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_SelectPointCloudInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Toposurface.
        /// </summary>
        public static string TopoFromPointCloud_Transaction {
            get {
                return ResourceManager.GetString("TopoFromPointCloud_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slope Grading.
        /// </summary>
        public static string Toposolid_SlopeGrading_Create {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding the outer bounds of the floor. Please try to simplify the floor geometry and try again..
        /// </summary>
        public static string Toposolid_SlopeGrading_ErrorFindingEdges {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_ErrorFindingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sorting floor bound edges. Please try to simplify the floor geometry and try again..
        /// </summary>
        public static string Toposolid_SlopeGrading_ErrorSortingEdges {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_ErrorSortingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stabilishing floor edges. Please try to simplify the floor geometry and try again..
        /// </summary>
        public static string Toposolid_SlopeGrading_NoFloorEdges {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_NoFloorEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any Topo Solid in the project. Please create at least one Topo Solid to use this tool..
        /// </summary>
        public static string Toposolid_SlopeGrading_NoTopoSolid {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_NoTopoSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a floor above or below a Topo Solid..
        /// </summary>
        public static string Toposolid_SlopeGrading_PickFloor {
            get {
                return ResourceManager.GetString("Toposolid_SlopeGrading_PickFloor", resourceCulture);
            }
        }
    }
}
