//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONBOXAppl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RibbonLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONBOXAppl.Properties.RibbonLanguage", typeof(RibbonLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_Onbox_Descrip {
            get {
                return ResourceManager.GetString("About_Onbox_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string About_Onbox_ToolTip {
            get {
                return ResourceManager.GetString("About_Onbox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Info.
        /// </summary>
        public static string About_Privacy {
            get {
                return ResourceManager.GetString("About_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample\nProjects.
        /// </summary>
        public static string About_SampleProjects {
            get {
                return ResourceManager.GetString("About_SampleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_SampleProjects_Descrip {
            get {
                return ResourceManager.GetString("About_SampleProjects_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder that contains the Onbox sample projects.
        /// </summary>
        public static string About_SampleProjects_ToolTip {
            get {
                return ResourceManager.GetString("About_SampleProjects_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_Site_Descrip {
            get {
                return ResourceManager.GetString("About_Site_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Onbox Website.
        /// </summary>
        public static string About_Site_ToolTip {
            get {
                return ResourceManager.GetString("About_Site_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package\nProject.
        /// </summary>
        public static string Manage_PackageProject {
            get {
                return ResourceManager.GetString("Manage_PackageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Manage_PackageProject_Descrip {
            get {
                return ResourceManager.GetString("Manage_PackageProject_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a zip file with all project related files.
        /// </summary>
        public static string Manage_PackageProject_ToolTip {
            get {
                return ResourceManager.GetString("Manage_PackageProject_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage_Title {
            get {
                return ResourceManager.GetString("Manage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Beams\nTo Levels.
        /// </summary>
        public static string ModifyElements_CopyBeamsToLevels {
            get {
                return ResourceManager.GetString("ModifyElements_CopyBeamsToLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command copies structural beams to the selected level from the selected structural beam level, all beams from the source level will be copied.
        /// </summary>
        public static string ModifyElements_CopyBeamsToLevels_Descrip {
            get {
                return ResourceManager.GetString("ModifyElements_CopyBeamsToLevels_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create beams selecting structural columns.
        /// </summary>
        public static string ModifyElements_CopyBeamsToLevels_ToolTip {
            get {
                return ResourceManager.GetString("ModifyElements_CopyBeamsToLevels_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Elements.
        /// </summary>
        public static string ModifyElements_JoinElements {
            get {
                return ResourceManager.GetString("ModifyElements_JoinElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModifyElements_JoinElements_Descrip {
            get {
                return ResourceManager.GetString("ModifyElements_JoinElements_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join structural and non structural elements.
        /// </summary>
        public static string ModifyElements_JoinElements_ToolTip {
            get {
                return ResourceManager.GetString("ModifyElements_JoinElements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Multiple Elements.
        /// </summary>
        public static string ModifyElements_JoinMultipleElements {
            get {
                return ResourceManager.GetString("ModifyElements_JoinMultipleElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Elements\nTo Join.
        /// </summary>
        public static string ModifyElements_SelectElementsToJoin {
            get {
                return ResourceManager.GetString("ModifyElements_SelectElementsToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModifyElements_SelectElementsToJoin_Descrip {
            get {
                return ResourceManager.GetString("ModifyElements_SelectElementsToJoin_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and join structural and non structural elements.
        /// </summary>
        public static string ModifyElements_SelectElementsToJoin_ToolTip {
            get {
                return ResourceManager.GetString("ModifyElements_SelectElementsToJoin_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Elements.
        /// </summary>
        public static string ModifyElements_Title {
            get {
                return ResourceManager.GetString("ModifyElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string MoreInfo_Title {
            get {
                return ResourceManager.GetString("MoreInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notififications_Title {
            get {
                return ResourceManager.GetString("Notififications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear\nNumbering.
        /// </summary>
        public static string RenumberElements_ClearParkingNumbering {
            get {
                return ResourceManager.GetString("RenumberElements_ClearParkingNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RenumberElements_ClearParkingNumbering_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_ClearParkingNumbering_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RenumberElements_ClearParkingNumbering_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_ClearParkingNumbering_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string RenumberElements_Columns {
            get {
                return ResourceManager.GetString("RenumberElements_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to automatically renumber structural columns.
        /// </summary>
        public static string RenumberElements_Columns_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_Columns_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber columns.
        /// </summary>
        public static string RenumberElements_Columns_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_Columns_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grids.
        /// </summary>
        public static string RenumberElements_Grids {
            get {
                return ResourceManager.GetString("RenumberElements_Grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to automatically renumber grids: A sequence of numbers or letters can be selected, including subletters and sub numbers. This command has also the ability to use a table to reorder and organize all grids.
        /// </summary>
        public static string RenumberElements_Grids_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_Grids_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Grids.
        /// </summary>
        public static string RenumberElements_Grids_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_Grids_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest\nSpaces.
        /// </summary>
        public static string RenumberElements_NearestSpaces {
            get {
                return ResourceManager.GetString("RenumberElements_NearestSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RenumberElements_NearestSpaces_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_NearestSpaces_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RenumberElements_NearestSpaces_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_NearestSpaces_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking\nSpaces.
        /// </summary>
        public static string RenumberElements_ParkingSpaces {
            get {
                return ResourceManager.GetString("RenumberElements_ParkingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams.
        /// </summary>
        public static string RenumberElements_RenumberBeams {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to automatically renumber structural beams.
        /// </summary>
        public static string RenumberElements_RenumberBeams_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberBeams_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Structural Beams.
        /// </summary>
        public static string RenumberElements_RenumberBeams_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberBeams_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Columns.
        /// </summary>
        public static string RenumberElements_RenumberColumns {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Parking Spaces.
        /// </summary>
        public static string RenumberElements_RenumberParkingSpaces {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberParkingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RenumberElements_RenumberParkingSpaces_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberParkingSpaces_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber parking spaces.
        /// </summary>
        public static string RenumberElements_RenumberParkingSpaces_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_RenumberParkingSpaces_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select\nColumns.
        /// </summary>
        public static string RenumberElements_SelectColumns {
            get {
                return ResourceManager.GetString("RenumberElements_SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to automatically renumber selected structural columns.
        /// </summary>
        public static string RenumberElements_SelectColumns_Descrip {
            get {
                return ResourceManager.GetString("RenumberElements_SelectColumns_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber selected columns.
        /// </summary>
        public static string RenumberElements_SelectColumns_ToolTip {
            get {
                return ResourceManager.GetString("RenumberElements_SelectColumns_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Elements.
        /// </summary>
        public static string RenumberElements_Title {
            get {
                return ResourceManager.GetString("RenumberElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beams.
        /// </summary>
        public static string StructuralElements_BeamsForBuilding {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsForBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command reads all walls in the current project or in a linked file to create structural beams in all chosen levels.
        /// </summary>
        public static string StructuralElements_BeamsForBuilding_Descrip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsForBuilding_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute beams on every valid wall on the building.
        /// </summary>
        public static string StructuralElements_BeamsForBuilding_ToolTip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsForBuilding_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams\nFrom Columns.
        /// </summary>
        public static string StructuralElements_BeamsFromColumns {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates structural beams from selected structural columns, the command creates the types automatically, it is possible to pre-establish the beam height, create them in a chain along with other options.
        /// </summary>
        public static string StructuralElements_BeamsFromColumns_Descrip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromColumns_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create structural beams from structural columns.
        /// </summary>
        public static string StructuralElements_BeamsFromColumns_ToolTip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromColumns_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams\nFrom Walls.
        /// </summary>
        public static string StructuralElements_BeamsFromWalls {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates structural beams from walls, it creates all types automatically, it is possible to pre-establish the beam height, join these beams with nearest walls and utilize linked files along with other options.
        /// </summary>
        public static string StructuralElements_BeamsFromWalls_Descrip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromWalls_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create beams selecting architectural walls.
        /// </summary>
        public static string StructuralElements_BeamsFromWalls_ToolTip {
            get {
                return ResourceManager.GetString("StructuralElements_BeamsFromWalls_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns\nFrom CAD.
        /// </summary>
        public static string StructuralElements_ColumnsFromCAD {
            get {
                return ResourceManager.GetString("StructuralElements_ColumnsFromCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates structural columns from linked 2D CAD files, it reads the closed rectangles and circles on the selected layer and restricts to the heights of the specified levels.
        /// </summary>
        public static string StructuralElements_ColumnsFromCAD_Descrip {
            get {
                return ResourceManager.GetString("StructuralElements_ColumnsFromCAD_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create structural columns from a CAD import or link.
        /// </summary>
        public static string StructuralElements_ColumnsFromCAD_ToolTip {
            get {
                return ResourceManager.GetString("StructuralElements_ColumnsFromCAD_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural Elements.
        /// </summary>
        public static string StructuralElements_Title {
            get {
                return ResourceManager.GetString("StructuralElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Grading\n By Pads.
        /// </summary>
        public static string Topography_SlopeByPads {
            get {
                return ResourceManager.GetString("Topography_SlopeByPads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates slope gradings from selected building pads, it is possible to define the angle and the number of iteration poins by each segment.
        /// </summary>
        public static string Topography_SlopeByPads_Descrip {
            get {
                return ResourceManager.GetString("Topography_SlopeByPads_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create slope grading from selected pads.
        /// </summary>
        public static string Topography_SlopeByPads_ToolTip {
            get {
                return ResourceManager.GetString("Topography_SlopeByPads_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface\nBy PointCloud.
        /// </summary>
        public static string Topography_SurfaceByPointCloud {
            get {
                return ResourceManager.GetString("Topography_SurfaceByPointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Topography_SurfaceByPointCloud_Descrip {
            get {
                return ResourceManager.GetString("Topography_SurfaceByPointCloud_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Toposurface from a selected PointCloud instance.
        /// </summary>
        public static string Topography_SurfaceByPointCloud_ToolTip {
            get {
                return ResourceManager.GetString("Topography_SurfaceByPointCloud_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topography.
        /// </summary>
        public static string Topography_Title {
            get {
                return ResourceManager.GetString("Topography_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Grading\nBy Floor.
        /// </summary>
        public static string Topography_TopoSolid_SlopeByFloor {
            get {
                return ResourceManager.GetString("Topography_TopoSolid_SlopeByFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command creates slope gradings from selected floors, it is possible to define the angle and the number of iteration poins by each segment.
        /// </summary>
        public static string Topography_TopoSolid_SlopeByFloor_Descrip {
            get {
                return ResourceManager.GetString("Topography_TopoSolid_SlopeByFloor_Descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create slope grading from selected floors.
        /// </summary>
        public static string Topography_TopoSolid_SlopeByFloor_ToolTip {
            get {
                return ResourceManager.GetString("Topography_TopoSolid_SlopeByFloor_ToolTip", resourceCulture);
            }
        }
    }
}
