//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONBOXAppl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ONBOXAppl.Properties.WindowLanguage", typeof(WindowLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is OnBox?
        ///
        ///Onbox is a free and open source Revit App that helps day to day tasks like renumbering elements, creating structural components, topo surface manipulations, and content management.
        ///
        ///Originally created in 2014 as a collection of macros to improve and speed up workflows for multi-story buildings, it had its first public release in September 2016 as a Revit Application. It became very popular in Brazil and other countries like Spain, Mexico, and Portugal, helping AEC students and profession [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Information {
            get {
                return ResourceManager.GetString("About_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnboxApp.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Type Dimensions.
        /// </summary>
        public static string BeamsForBuilding_BeamTypeDimensions {
            get {
                return ResourceManager.GetString("BeamsForBuilding_BeamTypeDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Beam Family.
        /// </summary>
        public static string BeamsForBuilding_ChooseBeamFamily {
            get {
                return ResourceManager.GetString("BeamsForBuilding_ChooseBeamFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Levels to be Renumbered.
        /// </summary>
        public static string BeamsForBuilding_ChooseLevelsToBeRenumbered {
            get {
                return ResourceManager.GetString("BeamsForBuilding_ChooseLevelsToBeRenumbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beams on Intermediate Levels.
        /// </summary>
        public static string BeamsForBuilding_CreateBeamsOnIntermediateLevels {
            get {
                return ResourceManager.GetString("BeamsForBuilding_CreateBeamsOnIntermediateLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string BeamsForBuilding_Height {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Standard Levels.
        /// </summary>
        public static string BeamsForBuilding_IgnoreStandardLevels {
            get {
                return ResourceManager.GetString("BeamsForBuilding_IgnoreStandardLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Walls with Width Less Than.
        /// </summary>
        public static string BeamsForBuilding_IgnoreWallsWidthLessThan {
            get {
                return ResourceManager.GetString("BeamsForBuilding_IgnoreWallsWidthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Selection.
        /// </summary>
        public static string BeamsForBuilding_Invert {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BeamsForBuilding_LevelName {
            get {
                return ResourceManager.GetString("BeamsForBuilding_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string BeamsForBuilding_LevelUse {
            get {
                return ResourceManager.GetString("BeamsForBuilding_LevelUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BeamsForBuilding_LinkedFileName {
            get {
                return ResourceManager.GetString("BeamsForBuilding_LinkedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Files.
        /// </summary>
        public static string BeamsForBuilding_LinkedFiles {
            get {
                return ResourceManager.GetString("BeamsForBuilding_LinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string BeamsForBuilding_Options {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string BeamsForBuilding_SelectAll {
            get {
                return ResourceManager.GetString("BeamsForBuilding_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string BeamsForBuilding_SelectNone {
            get {
                return ResourceManager.GetString("BeamsForBuilding_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Levels.
        /// </summary>
        public static string BeamsForBuilding_StandardLevels {
            get {
                return ResourceManager.GetString("BeamsForBuilding_StandardLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Beams For The Entire Building.
        /// </summary>
        public static string BeamsForBuilding_Title {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to Join Beams with Nearby Walls.
        /// </summary>
        public static string BeamsForBuilding_TryToJoin {
            get {
                return ResourceManager.GetString("BeamsForBuilding_TryToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string BeamsForBuilding_Width {
            get {
                return ResourceManager.GetString("BeamsForBuilding_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Standard Floors.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_ChooseStandardFloors {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_ChooseStandardFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Selection.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_Invert {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Standard?.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_IsStandard {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_IsStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level that Contains the Name.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_LevelsThatContainsName {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_LevelsThatContainsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually Pick Standard Floors.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_ManuallyPickStandardFloors {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_ManuallyPickStandardFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_MatchCase {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_Name {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_SelectAll {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_SelectNone {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_Standard {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Floors.
        /// </summary>
        public static string BeamsForBuildingLevelOptions_Title {
            get {
                return ResourceManager.GetString("BeamsForBuildingLevelOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        public static string BeamsFromColumns_Chain {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Beam Family.
        /// </summary>
        public static string BeamsFromColumns_ChooseBeamFamily {
            get {
                return ResourceManager.GetString("BeamsFromColumns_ChooseBeamFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BeamsFromColumns_Create {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Selected Column.
        /// </summary>
        public static string BeamsFromColumns_FirstSelectedColumn {
            get {
                return ResourceManager.GetString("BeamsFromColumns_FirstSelectedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Height.
        /// </summary>
        public static string BeamsFromColumns_FixedHeight {
            get {
                return ResourceManager.GetString("BeamsFromColumns_FixedHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Width.
        /// </summary>
        public static string BeamsFromColumns_FixedWidth {
            get {
                return ResourceManager.GetString("BeamsFromColumns_FixedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string BeamsFromColumns_Height {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string BeamsFromColumns_MoreOptions {
            get {
                return ResourceManager.GetString("BeamsFromColumns_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Selected Column.
        /// </summary>
        public static string BeamsFromColumns_SecondSelectedColumn {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SecondSelectedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Divided By.
        /// </summary>
        public static string BeamsFromColumns_SpanDividedBy {
            get {
                return ResourceManager.GetString("BeamsFromColumns_SpanDividedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams From Structural Columns.
        /// </summary>
        public static string BeamsFromColumns_Title {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string BeamsFromColumns_Width {
            get {
                return ResourceManager.GetString("BeamsFromColumns_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BeamsFromWalls_Create {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string BeamsFromWalls_Dimensions {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Height.
        /// </summary>
        public static string BeamsFromWalls_FixedHeight {
            get {
                return ResourceManager.GetString("BeamsFromWalls_FixedHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Width.
        /// </summary>
        public static string BeamsFromWalls_FixedWidth {
            get {
                return ResourceManager.GetString("BeamsFromWalls_FixedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string BeamsFromWalls_Height {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted.
        /// </summary>
        public static string BeamsFromWalls_Inverted {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join With Walls.
        /// </summary>
        public static string BeamsFromWalls_JoinWithWalls {
            get {
                return ResourceManager.GetString("BeamsFromWalls_JoinWithWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string BeamsFromWalls_Links {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Beam.
        /// </summary>
        public static string BeamsFromWalls_LowerBeam {
            get {
                return ResourceManager.GetString("BeamsFromWalls_LowerBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string BeamsFromWalls_MoreOptions {
            get {
                return ResourceManager.GetString("BeamsFromWalls_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string BeamsFromWalls_Position {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Divided by.
        /// </summary>
        public static string BeamsFromWalls_SpanDividedBy {
            get {
                return ResourceManager.GetString("BeamsFromWalls_SpanDividedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams From Walls.
        /// </summary>
        public static string BeamsFromWalls_Title {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To The Highest Opening.
        /// </summary>
        public static string BeamsFromWalls_ToTheHighestCasing {
            get {
                return ResourceManager.GetString("BeamsFromWalls_ToTheHighestCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Beam.
        /// </summary>
        public static string BeamsFromWalls_UpperBeam {
            get {
                return ResourceManager.GetString("BeamsFromWalls_UpperBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Width Added to.
        /// </summary>
        public static string BeamsFromWalls_WallWidthAddedTo {
            get {
                return ResourceManager.GetString("BeamsFromWalls_WallWidthAddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string BeamsFromWalls_Width {
            get {
                return ResourceManager.GetString("BeamsFromWalls_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Circular Family.
        /// </summary>
        public static string ColumnsFromCAD_ChooseCircularFamily {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_ChooseCircularFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Rectangular Family.
        /// </summary>
        public static string ColumnsFromCAD_ChooseRectangularFamily {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_ChooseRectangularFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose The Layer.
        /// </summary>
        public static string ColumnsFromCAD_ChooseTheLayer {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_ChooseTheLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose The Levels To Be Used.
        /// </summary>
        public static string ColumnsFromCAD_ChooseTheLevels {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_ChooseTheLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Selection.
        /// </summary>
        public static string ColumnsFromCAD_InvertSelection {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnsFromCAD_LevelName {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string ColumnsFromCAD_LevelUse {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_LevelUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ColumnsFromCAD_SelectAll {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string ColumnsFromCAD_SelectNone {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural Columns From CAD.
        /// </summary>
        public static string ColumnsFromCAD_Title {
            get {
                return ResourceManager.GetString("ColumnsFromCAD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyElements_CopyAction {
            get {
                return ResourceManager.GetString("CopyElements_CopyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Beams on Target Level.
        /// </summary>
        public static string CopyElements_DeleteBeamsOnTargetLevel {
            get {
                return ResourceManager.GetString("CopyElements_DeleteBeamsOnTargetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Beams.
        /// </summary>
        public static string CopyElements_Title {
            get {
                return ResourceManager.GetString("CopyElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Toposurface.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_GenerateTopo {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_GenerateTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_Horizontal {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Distance.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_IterationDistance {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_IterationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_Iterations {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Toposurface from Point Cloud.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_Title {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_TotalDistance {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string CreateTopoSurfacePointCloud_Vertical {
            get {
                return ResourceManager.GetString("CreateTopoSurfacePointCloud_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the app ran through an unmanaged error, please, contact us at contato@onboxdesign.com.br with the report below and as much more information as you can, so we can try to fix the issue..
        /// </summary>
        public static string Exceptions_DefaultMessage {
            get {
                return ResourceManager.GetString("Exceptions_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string Exceptions_Report {
            get {
                return ResourceManager.GetString("Exceptions_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops!.
        /// </summary>
        public static string Exceptions_Title {
            get {
                return ResourceManager.GetString("Exceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams.
        /// </summary>
        public static string JoinUnjoin_Beams {
            get {
                return ResourceManager.GetString("JoinUnjoin_Beams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string JoinUnjoin_Columns {
            get {
                return ResourceManager.GetString("JoinUnjoin_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down To Level.
        /// </summary>
        public static string JoinUnjoin_DownToLevel {
            get {
                return ResourceManager.GetString("JoinUnjoin_DownToLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Category.
        /// </summary>
        public static string JoinUnjoin_FirstCategory {
            get {
                return ResourceManager.GetString("JoinUnjoin_FirstCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string JoinUnjoin_Floors {
            get {
                return ResourceManager.GetString("JoinUnjoin_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Level.
        /// </summary>
        public static string JoinUnjoin_FromLevel {
            get {
                return ResourceManager.GetString("JoinUnjoin_FromLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinUnjoin_JoinAction {
            get {
                return ResourceManager.GetString("JoinUnjoin_JoinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Category.
        /// </summary>
        public static string JoinUnjoin_SecondCategory {
            get {
                return ResourceManager.GetString("JoinUnjoin_SecondCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join / Unjoin Elements.
        /// </summary>
        public static string JoinUnjoin_Title {
            get {
                return ResourceManager.GetString("JoinUnjoin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Level.
        /// </summary>
        public static string JoinUnjoin_ToLevel {
            get {
                return ResourceManager.GetString("JoinUnjoin_ToLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjoin.
        /// </summary>
        public static string JoinUnjoin_UnjoinAction {
            get {
                return ResourceManager.GetString("JoinUnjoin_UnjoinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Level.
        /// </summary>
        public static string JoinUnjoin_UpToLevel {
            get {
                return ResourceManager.GetString("JoinUnjoin_UpToLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls.
        /// </summary>
        public static string JoinUnjoin_Walls {
            get {
                return ResourceManager.GetString("JoinUnjoin_Walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string JoinUnjoinSelected_All {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams.
        /// </summary>
        public static string JoinUnjoinSelected_Beams {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Beams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string JoinUnjoinSelected_Columns {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string JoinUnjoinSelected_Floors {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinUnjoinSelected_Join {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinUnjoinSelected_JoinAction {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_JoinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join With.
        /// </summary>
        public static string JoinUnjoinSelected_JoinWith {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_JoinWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Element.
        /// </summary>
        public static string JoinUnjoinSelected_MarkedElement {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_MarkedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Elements.
        /// </summary>
        public static string JoinUnjoinSelected_MarkedElements {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_MarkedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join / Unjoin Elements.
        /// </summary>
        public static string JoinUnjoinSelected_Title {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjoin.
        /// </summary>
        public static string JoinUnjoinSelected_UnjoinAction {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_UnjoinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls.
        /// </summary>
        public static string JoinUnjoinSelected_Walls {
            get {
                return ResourceManager.GetString("JoinUnjoinSelected_Walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my Account.
        /// </summary>
        public static string Privacy_EditAccount {
            get {
                return ResourceManager.GetString("Privacy_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnboxApp only stores your email from a notification system that the Autodesk Exchange App Store sends to it when you download the application. This is the only instance where we have any identification of who is the using the application though, after download and installation, NO tracking of any type is used, not even for diagnostics or statistics.  The exact source code that you can audit on https://github.com/engthiago/OnboxApp is the one deployed to your computer.
        ///
        ///Your email is only stored in our own [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Privacy_Information {
            get {
                return ResourceManager.GetString("Privacy_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberBeamLevelOptions_Name {
            get {
                return ResourceManager.GetString("RenumberBeamLevelOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering by level.
        /// </summary>
        public static string RenumberBeamLevelOptions_NumberingByLevel {
            get {
                return ResourceManager.GetString("RenumberBeamLevelOptions_NumberingByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberBeamLevelOptions_Prefix {
            get {
                return ResourceManager.GetString("RenumberBeamLevelOptions_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberBeamLevelOptions_Title {
            get {
                return ResourceManager.GetString("RenumberBeamLevelOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberBeamLevelOptions_Use {
            get {
                return ResourceManager.GetString("RenumberBeamLevelOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places.
        /// </summary>
        public static string RenumberBeams_DecimalPlaces {
            get {
                return ResourceManager.GetString("RenumberBeams_DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoizontals First.
        /// </summary>
        public static string RenumberBeams_HorizontalsFirst {
            get {
                return ResourceManager.GetString("RenumberBeams_HorizontalsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberBeams_LevelOptions {
            get {
                return ResourceManager.GetString("RenumberBeams_LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rule.
        /// </summary>
        public static string RenumberBeams_NoRule {
            get {
                return ResourceManager.GetString("RenumberBeams_NoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string RenumberBeams_Renumber {
            get {
                return ResourceManager.GetString("RenumberBeams_Renumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumbering Rule.
        /// </summary>
        public static string RenumberBeams_RenumberingRule {
            get {
                return ResourceManager.GetString("RenumberBeams_RenumberingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Beams.
        /// </summary>
        public static string RenumberBeams_Title {
            get {
                return ResourceManager.GetString("RenumberBeams_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Options.
        /// </summary>
        public static string RenumberBeams_TypeOptions {
            get {
                return ResourceManager.GetString("RenumberBeams_TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticals First.
        /// </summary>
        public static string RenumberBeams_VerticalsFirst {
            get {
                return ResourceManager.GetString("RenumberBeams_VerticalsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberBeamsTypeOptions_Name {
            get {
                return ResourceManager.GetString("RenumberBeamsTypeOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberBeamsTypeOptions_Prefix {
            get {
                return ResourceManager.GetString("RenumberBeamsTypeOptions_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict beam types to be renumbered.
        /// </summary>
        public static string RenumberBeamsTypeOptions_Restrict {
            get {
                return ResourceManager.GetString("RenumberBeamsTypeOptions_Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Beam Types.
        /// </summary>
        public static string RenumberBeamsTypeOptions_Title {
            get {
                return ResourceManager.GetString("RenumberBeamsTypeOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberBeamsTypeOptions_Use {
            get {
                return ResourceManager.GetString("RenumberBeamsTypeOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concatenation.
        /// </summary>
        public static string RenumberColumns_Concatenation {
            get {
                return ResourceManager.GetString("RenumberColumns_Concatenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downwards.
        /// </summary>
        public static string RenumberColumns_Downwards {
            get {
                return ResourceManager.GetString("RenumberColumns_Downwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Options.
        /// </summary>
        public static string RenumberColumns_GeneralOptions {
            get {
                return ResourceManager.GetString("RenumberColumns_GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string RenumberColumns_LevelConcatenator {
            get {
                return ResourceManager.GetString("RenumberColumns_LevelConcatenator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Label.
        /// </summary>
        public static string RenumberColumns_LevelLabel {
            get {
                return ResourceManager.GetString("RenumberColumns_LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string RenumberColumns_LevelLabeler {
            get {
                return ResourceManager.GetString("RenumberColumns_LevelLabeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberColumns_LevelOptions {
            get {
                return ResourceManager.GetString("RenumberColumns_LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering Rule.
        /// </summary>
        public static string RenumberColumns_NumberingRule {
            get {
                return ResourceManager.GetString("RenumberColumns_NumberingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string RenumberColumns_Renumber {
            get {
                return ResourceManager.GetString("RenumberColumns_Renumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Columns.
        /// </summary>
        public static string RenumberColumns_Title {
            get {
                return ResourceManager.GetString("RenumberColumns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Options.
        /// </summary>
        public static string RenumberColumns_TypeOptions {
            get {
                return ResourceManager.GetString("RenumberColumns_TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upwards.
        /// </summary>
        public static string RenumberColumns_Upwards {
            get {
                return ResourceManager.GetString("RenumberColumns_Upwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns Level Options.
        /// </summary>
        public static string RenumberColumnsLevelOptions_ColumnsLevelOptions {
            get {
                return ResourceManager.GetString("RenumberColumnsLevelOptions_ColumnsLevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string RenumberColumnsLevelOptions_Label {
            get {
                return ResourceManager.GetString("RenumberColumnsLevelOptions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberColumnsLevelOptions_Name {
            get {
                return ResourceManager.GetString("RenumberColumnsLevelOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberColumnsLevelOptions_Title {
            get {
                return ResourceManager.GetString("RenumberColumnsLevelOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberColumnsLevelOptions_Use {
            get {
                return ResourceManager.GetString("RenumberColumnsLevelOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concatenation.
        /// </summary>
        public static string RenumberColumnsSelection_Concatenation {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Concatenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string RenumberColumnsSelection_Concatenator {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Concatenator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downwards.
        /// </summary>
        public static string RenumberColumnsSelection_Downwards {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Downwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Options.
        /// </summary>
        public static string RenumberColumnsSelection_GeneralOptions {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess.
        /// </summary>
        public static string RenumberColumnsSelection_Guess {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Label.
        /// </summary>
        public static string RenumberColumnsSelection_LevelLabel {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string RenumberColumnsSelection_LevelLabeler {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_LevelLabeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberColumnsSelection_LevelOptions {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Numbering.
        /// </summary>
        public static string RenumberColumnsSelection_NextNumbering {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_NextNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumbering Rule.
        /// </summary>
        public static string RenumberColumnsSelection_RenumberingRule {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_RenumberingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Columns by Selection.
        /// </summary>
        public static string RenumberColumnsSelection_Title {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Options.
        /// </summary>
        public static string RenumberColumnsSelection_TypeOptions {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upwards.
        /// </summary>
        public static string RenumberColumnsSelection_Upwards {
            get {
                return ResourceManager.GetString("RenumberColumnsSelection_Upwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Types To Be Renumbered.
        /// </summary>
        public static string RenumberColumnsTypeOptions_ColumnTypesToBeRenumbered {
            get {
                return ResourceManager.GetString("RenumberColumnsTypeOptions_ColumnTypesToBeRenumbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberColumnsTypeOptions_Name {
            get {
                return ResourceManager.GetString("RenumberColumnsTypeOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberColumnsTypeOptions_Prefix {
            get {
                return ResourceManager.GetString("RenumberColumnsTypeOptions_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types To Be Renumbered.
        /// </summary>
        public static string RenumberColumnsTypeOptions_Title {
            get {
                return ResourceManager.GetString("RenumberColumnsTypeOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberColumnsTypeOptions_Use {
            get {
                return ResourceManager.GetString("RenumberColumnsTypeOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Orientation.
        /// </summary>
        public static string RenumberGrids_FlipOrientation {
            get {
                return ResourceManager.GetString("RenumberGrids_FlipOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Grids.
        /// </summary>
        public static string RenumberGrids_HorizontalGrids {
            get {
                return ResourceManager.GetString("RenumberGrids_HorizontalGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Orientation.
        /// </summary>
        public static string RenumberGrids_InvertOrientation {
            get {
                return ResourceManager.GetString("RenumberGrids_InvertOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string RenumberGrids_Letters {
            get {
                return ResourceManager.GetString("RenumberGrids_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string RenumberGrids_MoreOptions {
            get {
                return ResourceManager.GetString("RenumberGrids_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string RenumberGrids_NewNumbering {
            get {
                return ResourceManager.GetString("RenumberGrids_NewNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string RenumberGrids_Numbers {
            get {
                return ResourceManager.GetString("RenumberGrids_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string RenumberGrids_Orientation {
            get {
                return ResourceManager.GetString("RenumberGrids_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string RenumberGrids_PrevNumbering {
            get {
                return ResourceManager.GetString("RenumberGrids_PrevNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber List.
        /// </summary>
        public static string RenumberGrids_RenumberList {
            get {
                return ResourceManager.GetString("RenumberGrids_RenumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Order.
        /// </summary>
        public static string RenumberGrids_RestoreOrder {
            get {
                return ResourceManager.GetString("RenumberGrids_RestoreOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Orientation.
        /// </summary>
        public static string RenumberGrids_RestoreOrientation {
            get {
                return ResourceManager.GetString("RenumberGrids_RestoreOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Numbering.
        /// </summary>
        public static string RenumberGrids_SubNumbering {
            get {
                return ResourceManager.GetString("RenumberGrids_SubNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Grids.
        /// </summary>
        public static string RenumberGrids_Title {
            get {
                return ResourceManager.GetString("RenumberGrids_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Grids.
        /// </summary>
        public static string RenumberGrids_VerticalGrids {
            get {
                return ResourceManager.GetString("RenumberGrids_VerticalGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downwards.
        /// </summary>
        public static string RenumberPark_Downwards {
            get {
                return ResourceManager.GetString("RenumberPark_Downwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberPark_LevelOptions {
            get {
                return ResourceManager.GetString("RenumberPark_LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        public static string RenumberPark_Renumber {
            get {
                return ResourceManager.GetString("RenumberPark_Renumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering Order.
        /// </summary>
        public static string RenumberPark_RenumberingOrder {
            get {
                return ResourceManager.GetString("RenumberPark_RenumberingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Parking Spaces.
        /// </summary>
        public static string RenumberPark_Title {
            get {
                return ResourceManager.GetString("RenumberPark_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Options.
        /// </summary>
        public static string RenumberPark_TypeOptions {
            get {
                return ResourceManager.GetString("RenumberPark_TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upwards.
        /// </summary>
        public static string RenumberPark_Upwards {
            get {
                return ResourceManager.GetString("RenumberPark_Upwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RenumberParkBlock_All {
            get {
                return ResourceManager.GetString("RenumberParkBlock_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess Next.
        /// </summary>
        public static string RenumberParkBlock_GuessNext {
            get {
                return ResourceManager.GetString("RenumberParkBlock_GuessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string RenumberParkBlock_Level {
            get {
                return ResourceManager.GetString("RenumberParkBlock_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Numbering.
        /// </summary>
        public static string RenumberParkBlock_NextNumbering {
            get {
                return ResourceManager.GetString("RenumberParkBlock_NextNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        public static string RenumberParkBlock_Numbering {
            get {
                return ResourceManager.GetString("RenumberParkBlock_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberParkBlock_Prefix {
            get {
                return ResourceManager.GetString("RenumberParkBlock_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Parking Spaces.
        /// </summary>
        public static string RenumberParkBlock_Title {
            get {
                return ResourceManager.GetString("RenumberParkBlock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RenumberParkClear_All {
            get {
                return ResourceManager.GetString("RenumberParkClear_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string RenumberParkClear_Level {
            get {
                return ResourceManager.GetString("RenumberParkClear_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string RenumberParkClear_Options {
            get {
                return ResourceManager.GetString("RenumberParkClear_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Numbering.
        /// </summary>
        public static string RenumberParkClear_Title {
            get {
                return ResourceManager.GetString("RenumberParkClear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent numbering by level.
        /// </summary>
        public static string RenumberParkLevelOptions_LevelIndependent {
            get {
                return ResourceManager.GetString("RenumberParkLevelOptions_LevelIndependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberParkLevelOptions_Name {
            get {
                return ResourceManager.GetString("RenumberParkLevelOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberParkLevelOptions_Prefix {
            get {
                return ResourceManager.GetString("RenumberParkLevelOptions_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Options.
        /// </summary>
        public static string RenumberParkLevelOptions_Title {
            get {
                return ResourceManager.GetString("RenumberParkLevelOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberParkLevelOptions_Use {
            get {
                return ResourceManager.GetString("RenumberParkLevelOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RenumberParkTypeOptions_Name {
            get {
                return ResourceManager.GetString("RenumberParkTypeOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string RenumberParkTypeOptions_Prefix {
            get {
                return ResourceManager.GetString("RenumberParkTypeOptions_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict types of parkings to be renumbered.
        /// </summary>
        public static string RenumberParkTypeOptions_Restrict {
            get {
                return ResourceManager.GetString("RenumberParkTypeOptions_Restrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Options.
        /// </summary>
        public static string RenumberParkTypeOptions_Title {
            get {
                return ResourceManager.GetString("RenumberParkTypeOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RenumberParkTypeOptions_Use {
            get {
                return ResourceManager.GetString("RenumberParkTypeOptions_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slope Gradings.
        /// </summary>
        public static string SlopeGrading_CreateSlopeGradings {
            get {
                return ResourceManager.GetString("SlopeGrading_CreateSlopeGradings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Slope Angle (Degrees).
        /// </summary>
        public static string SlopeGrading_MaxAngle {
            get {
                return ResourceManager.GetString("SlopeGrading_MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance Between Points (Meters).
        /// </summary>
        public static string SlopeGrading_MaxDistance {
            get {
                return ResourceManager.GetString("SlopeGrading_MaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Creation.
        /// </summary>
        public static string SlopeGrading_MultiplePads {
            get {
                return ResourceManager.GetString("SlopeGrading_MultiplePads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Grading by Pads.
        /// </summary>
        public static string SlopeGrading_Title {
            get {
                return ResourceManager.GetString("SlopeGrading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toposolid Grading by Floors.
        /// </summary>
        public static string ToposolidSolidGrading_Title {
            get {
                return ResourceManager.GetString("ToposolidSolidGrading_Title", resourceCulture);
            }
        }
    }
}
